# --- 反映に再起動が必要な物 ---
[Request]
avg_image_min = 4
avg_image_max = 64
avg_image_default = 16

[Sprinkler]
delay_ms = 200
quantify_size = 32

# --- 即時反映 ---
[Sprinkler.Asp]
min = 0.25
max = 16.0
diff = 0.1

[Sprinkler.Collect]
area_ratio = 4
enum_buckets = 5
enum_nimage = 10
aux_image = 8

[GeneWorker]
scale_min = 0.25
scale_max = 1.0
iteration = 32

[GeneWorker.NParent]
min = 16
x = 1
y = 1

[GeneWorker.NChild]
min = 32
x = 2
y = 0

[GeneWorker.Population]
ratio = 2

[GeneWorker.Mutate]
probability = 0.06
probability_path = 0.5

[GeneWorker.Fit]
fit_scale = 3.0
